// <auto-generated />
namespace MvcApplication141.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class DatabaseCreated : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DatabaseCreated));
        
        string IMigrationMetadata.Id
        {
            get { return "201210161847166_Database Created"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
